
const store={
 get(k,f){try{return JSON.parse(localStorage.getItem('studexa_'+k))??f}catch(e){return f}},
 set(k,v){localStorage.setItem('studexa_'+k,JSON.stringify(v))}
};
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function code(prefix='SCH'){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let p=()=>Array.from({length:4},()=>chars[Math.floor(Math.random()*chars.length)]).join('');return `${prefix}-${p()}-${p()}`}
function audit(action,school='Studexa Manager'){const logs=store.get('audit',[]);logs.unshift({time:new Date().toLocaleString(),school,action});store.set('audit',logs.slice(0,120))}
function seed(){
 if(!store.get('requests',null))store.set('requests',[{id:'REQ-1001',school:'Westview Secondary',type:'Secondary',admin:'Morgan Reed',email:'admin@westview.example',website:'westview.example',students:842,products:['Maths','Science'],microsoft:true,domain:'westview.example',status:'Pending',submitted:'Today 19:42'}]);
 if(!store.get('schools',null))store.set('schools',[{id:'WV-28419',name:'Demo Academy',adminEmail:'admin@demoacademy.example',code:'DEM0-7K4P-2MXQ',status:'Active',microsoft:true,domain:'demoacademy.example',maths:true,science:true,students:842,teachers:67,classes:38}]);
 if(!store.get('teachers',null))store.set('teachers',[{name:'Miss Carter',email:'m.carter@demoacademy.example',dept:'Maths & Science',products:'Maths, Science',role:'Teacher'},{name:'Mr Patel',email:'r.patel@demoacademy.example',dept:'Mathematics',products:'Maths',role:'Head of Department'}]);
 if(!store.get('students',null))store.set('students',[{first:'Jamie',last:'Smith',email:'jamie.smith@demoacademy.example',year:'9',tutor:'9A',studentId:'100392',maths:'9M1',science:'9S1'},{first:'Emily',last:'Clarke',email:'emily.clarke@demoacademy.example',year:'9',tutor:'9A',studentId:'100393',maths:'9M1',science:'9S1'}]);
 if(!store.get('classes',null))store.set('classes',[{name:'9M1',subject:'Studexa Maths',teacher:'Miss Carter',year:'9',students:31},{name:'9S1',subject:'Studexa Science',teacher:'Miss Carter',year:'9',students:31},{name:'10M2',subject:'Studexa Maths',teacher:'Mr Patel',year:'10',students:29}]);
}
seed();

function navTabs(){document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('[data-panel]').forEach(p=>p.classList.add('hidden'));document.querySelector(`[data-panel="${b.dataset.tab}"]`)?.classList.remove('hidden')}))}

function requestInit(){const f=document.querySelector('#schoolRequest');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(f);let reqs=store.get('requests',[]);let id='REQ-'+(1000+reqs.length+1);let obj={id,school:fd.get('school'),type:fd.get('type'),admin:fd.get('admin'),email:fd.get('email'),website:fd.get('website'),students:Number(fd.get('students')||0),products:[...f.querySelectorAll('input[name=product]:checked')].map(x=>x.value),microsoft:fd.get('microsoft')==='yes',domain:fd.get('domain')||'',status:'Pending',submitted:new Date().toLocaleString()};reqs.unshift(obj);store.set('requests',reqs);audit('School request submitted',obj.school);f.reset();document.querySelector('#requestResult').innerHTML=`<div class="success"><strong>Request received.</strong> Reference ${esc(id)}. In production this would be reviewed in Studexa Manager and the school admin would receive an activation code by email.</div>`})}

function managerInit(){const el=document.querySelector('#requestRows');if(!el)return;renderManager();}
function renderManager(){let reqs=store.get('requests',[]),schools=store.get('schools',[]),logs=store.get('audit',[]);document.querySelector('#pendingCount').textContent=reqs.filter(x=>x.status==='Pending').length;document.querySelector('#schoolCount').textContent=schools.length;document.querySelector('#requestRows').innerHTML=reqs.map(r=>`<tr><td><strong>${esc(r.school)}</strong><div class="tiny">${esc(r.id)}</div></td><td>${esc(r.admin)}<div class="tiny">${esc(r.email)}</div></td><td>${r.products.map(x=>`<span class="tag">${esc(x)}</span>`).join(' ')}</td><td>${r.microsoft?'Microsoft 365':'Code login'}</td><td><span class="tag ${r.status==='Pending'?'amber':'green'}">${esc(r.status)}</span></td><td>${r.status==='Pending'?`<button class="btn primary small" onclick="approve('${r.id}')">Approve</button>`:`<span class="tiny">Processed</span>`}</td></tr>`).join('')||'<tr><td colspan="6">No requests</td></tr>';
 document.querySelector('#schoolRows').innerHTML=schools.map(s=>`<tr><td><strong>${esc(s.name)}</strong><div class="tiny">${esc(s.id)}</div></td><td>${s.status}</td><td>${s.maths?'Maths ':''}${s.science?'Science':''}</td><td>${s.microsoft?'Enabled':'Off'}<div class="tiny">${esc(s.domain||'')}</div></td><td><button class="btn secondary small" onclick="toggleEntitlement('${s.id}','maths')">Maths</button> <button class="btn secondary small" onclick="toggleEntitlement('${s.id}','science')">Science</button></td></tr>`).join('');
 document.querySelector('#auditRows').innerHTML=logs.slice(0,12).map(l=>`<div class="rowitem"><div class="grow"><strong>${esc(l.school)}</strong><div class="tiny">${esc(l.action)}</div></div><div class="tiny">${esc(l.time)}</div></div>`).join('')||'<div class="empty">Audit events will appear here.</div>';
}
window.approve=function(id){let reqs=store.get('requests',[]),schools=store.get('schools',[]);let r=reqs.find(x=>x.id===id);if(!r)return;r.status='Approved';let id2=(r.school.slice(0,2).toUpperCase().replace(/[^A-Z]/g,'')||'SC')+'-'+Math.floor(10000+Math.random()*89999);let c=code('ACT');schools.unshift({id:id2,name:r.school,adminEmail:r.email,code:c,status:'Active',microsoft:r.microsoft,domain:r.domain,maths:r.products.includes('Maths'),science:r.products.includes('Science'),students:r.students,teachers:0,classes:0});store.set('requests',reqs);store.set('schools',schools);audit(`Approved request; activation code ${c}`,r.school);document.querySelector('#approvalCode').innerHTML=`<div class="success"><strong>${esc(r.school)} approved.</strong><br><br><span class="codebox">${esc(c)}</span><br><span class="tiny">Demo only: production stores a one-way hash of the activation token, not the plaintext code.</span></div>`;renderManager()}
window.toggleEntitlement=function(id,key){let schools=store.get('schools',[]);let s=schools.find(x=>x.id===id);if(s){s[key]=!s[key];store.set('schools',schools);audit(`${key} entitlement ${s[key]?'enabled':'disabled'}`,s.name);renderManager()}}

function adminInit(){if(!document.querySelector('#teacherRows'))return;renderAdmin();navTabs();document.querySelector('#teacherForm')?.addEventListener('submit',e=>{e.preventDefault();let fd=new FormData(e.target),t=store.get('teachers',[]);t.push({name:fd.get('name'),email:fd.get('email'),dept:fd.get('dept'),products:[...e.target.querySelectorAll('input[name=products]:checked')].map(x=>x.value).join(', '),role:fd.get('role')});store.set('teachers',t);audit('Teacher invited', 'Demo Academy');e.target.reset();renderAdmin()});
 document.querySelector('#studentCsv')?.addEventListener('change',importCsv);document.querySelector('#classForm')?.addEventListener('submit',e=>{e.preventDefault();let fd=new FormData(e.target),a=store.get('classes',[]);a.push({name:fd.get('name'),subject:fd.get('subject'),teacher:fd.get('teacher'),year:fd.get('year'),students:Number(fd.get('students')||0)});store.set('classes',a);audit('Class created: '+fd.get('name'),'Demo Academy');e.target.reset();renderAdmin()});
 document.querySelector('#ssoForm')?.addEventListener('submit',e=>{e.preventDefault();let fd=new FormData(e.target),schools=store.get('schools',[]),s=schools[0];if(s){s.domain=fd.get('domain');s.microsoft=fd.get('enabled')==='on';store.set('schools',schools);audit('Microsoft organisation settings updated','Demo Academy');document.querySelector('#ssoResult').innerHTML='<div class="success">Microsoft organisation settings saved. In production the tenant/domain is validated through Microsoft Entra before SSO is enabled.</div>'}})
}
function renderAdmin(){let teachers=store.get('teachers',[]),students=store.get('students',[]),classes=store.get('classes',[]);document.querySelector('#teacherCount').textContent=teachers.length;document.querySelector('#studentCount').textContent=students.length;document.querySelector('#classCount').textContent=classes.length;document.querySelector('#teacherRows').innerHTML=teachers.map((t,i)=>`<tr><td><strong>${esc(t.name)}</strong></td><td>${esc(t.email)}</td><td>${esc(t.dept)}</td><td>${esc(t.products)}</td><td>${esc(t.role)}</td><td><button class="btn danger small" onclick="removeTeacher(${i})">Remove</button></td></tr>`).join('');document.querySelector('#studentRows').innerHTML=students.slice(0,100).map((s,i)=>`<tr><td>${esc(s.first)} ${esc(s.last)}</td><td>${esc(s.email)}</td><td>Y${esc(s.year)}</td><td>${esc(s.tutor)}</td><td>${esc(s.maths)}</td><td>${esc(s.science)}</td></tr>`).join('');document.querySelector('#classRows').innerHTML=classes.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.subject)}</td><td>${esc(c.teacher)}</td><td>Y${esc(c.year)}</td><td>${c.students}</td></tr>`).join('')}
window.removeTeacher=function(i){let t=store.get('teachers',[]);let x=t.splice(i,1)[0];store.set('teachers',t);audit('Teacher removed: '+(x?.email||''),'Demo Academy');renderAdmin()}
function importCsv(e){let file=e.target.files[0];if(!file)return;let reader=new FileReader();reader.onload=()=>{let lines=reader.result.trim().split(/\r?\n/);let headers=lines.shift().split(',').map(x=>x.trim());let required=['first_name','last_name','email','year_group','tutor_group','student_id','maths_class','science_class'];let miss=required.filter(x=>!headers.includes(x));if(miss.length){document.querySelector('#importResult').innerHTML=`<div class="dangerbox">Missing columns: ${miss.join(', ')}</div>`;return}let arr=store.get('students',[]);let added=0;for(let line of lines){let vals=line.split(',');let o=Object.fromEntries(headers.map((h,i)=>[h,(vals[i]||'').trim()]));if(!o.email)continue;arr.push({first:o.first_name,last:o.last_name,email:o.email,year:o.year_group,tutor:o.tutor_group,studentId:o.student_id,maths:o.maths_class,science:o.science_class});added++}store.set('students',arr);audit(`CSV imported: ${added} students`,'Demo Academy');document.querySelector('#importResult').innerHTML=`<div class="success">Imported ${added} students successfully.</div>`;renderAdmin()};reader.readAsText(file)}

document.addEventListener('DOMContentLoaded',()=>{requestInit();managerInit();adminInit();navTabs()});
